# Generated by Django 5.2.4 on 2025-08-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_alter_challenge_status'),
        ('users', '0003_userprofile_challenges_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChalennges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(auto_created=True)),
                ('end_time', models.TimeField(auto_now=True)),
                ('challenge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenge.challenge')),
                ('users', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
