# Generated by Django 5.2.4 on 2025-08-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_alter_challenge_status'),
        ('users', '0004_userchalennges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChalennges',
            new_name='UserChallenges',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='challenges',
            field=models.ManyToManyField(blank=True, to='challenge.challenge'),
        ),
    ]
