# Generated by Django 5.2.4 on 2025-07-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True, max_length=15, null=True),
        ),
    ]
