# Generated by Django 5.2.4 on 2025-07-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_challenge_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='slug',
            field=models.SlugField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
