# Generated by Django 5.2.4 on 2025-08-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_alter_challenge_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('done', 'done')], null=True),
        ),
    ]
