# Generated by Django 5.2.4 on 2025-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_challenge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('done', 'done'), ('inprogress', 'IN PROGRESS'), ('canceled', 'CANCELED'), ('delayed', 'DELAYED')], null=True),
        ),
    ]
